insert into pais values(default, 'Sin Pais');
insert into pais values(default, 'ARGENTINA');
insert into pais values(default, 'BRASIL');
insert into pais values(default, 'PARAGUAY');
insert into pais values(default, 'URUGUAY');
insert into pais values(default, 'CHILE');
insert into pais values(default, 'BOLIVIA');
insert into pais values(default, 'PERU');
insert into pais values(default, 'COLOMBIA');
insert into pais values(default, 'VENEZUELA');
insert into pais values(default, 'FRANCIA');
insert into pais values(default, 'ALEMANIA');
insert into pais values(default, 'LITUANIA');
insert into pais values(default, 'ESPAÑA');
insert into pais values(default, 'NICARAGUA');
insert into pais values(default, 'MEXICO');
insert into pais values(default, 'ESTADOS UNIDOS');
insert into pais values(default, 'ITALIA');
insert into pais values(default, 'RUSIA');
insert into pais values(default, 'POLONIA');


insert into provincia values(default, 1, 'Sin Provincia');
insert into provincia values(default, 2, 'ENTRE RIOS');
insert into provincia values(default, 2, 'BUENOS AIRES');
insert into provincia values(default, 2, 'CATAMARCA');
insert into provincia values(default, 2, 'CHACO');
insert into provincia values(default, 2, 'CHUBUT');
insert into provincia values(default, 2, 'CORDOBA');
insert into provincia values(default, 2, 'CORRIENTES');
insert into provincia values(default, 2, 'FORMOSA');
insert into provincia values(default, 2, 'JUJUY');
insert into provincia values(default, 2, 'LA PAMPA');
insert into provincia values(default, 2, 'LA RIOJA');
insert into provincia values(default, 2, 'MENDOZA');
insert into provincia values(default, 2, 'MISIONES');
insert into provincia values(default, 2, 'NEUQUEN');
insert into provincia values(default, 2, 'RIO NEGRO');
insert into provincia values(default, 2, 'SALTA');
insert into provincia values(default, 2, 'SAN JUAN');
insert into provincia values(default, 2, 'SAN LUIS');
insert into provincia values(default, 2, 'SANTA CRUZ');
insert into provincia values(default, 2, 'SANTA FE');
insert into provincia values(default, 2, 'SANTIAGO DEL ESTERO');
insert into provincia values(default, 2, 'TIERRA DEL FUEGO');
insert into provincia values(default, 2, 'TUCUMAN');
insert into provincia values(default, 3, 'SANTA CATARINA');
insert into provincia values(default, 3, 'MATO GROSSO DEL SUR');
insert into provincia values(default, 3, 'SERGIPE');
insert into provincia values(default, 3, 'PARANA');
insert into provincia values(default, 3, 'SAN PABLO');
insert into provincia values(default, 3, 'RIO DE JANEIRO');
insert into provincia values(default, 3, 'RIO GRANDE DO SUL');
insert into provincia values(default, 4, 'ALTO PARANA');
insert into provincia values(default, 4, 'ASUNCIÓN');
insert into provincia values(default, 4, 'CAAZAPÁ');
insert into provincia values(default, 4, 'CAAGUAZU');
insert into provincia values(default, 4, 'CENTRAL');
insert into provincia values(default, 4, 'PARAGUARÍ');
insert into provincia values(default, 4, 'GUAIRÁ');
insert into provincia values(default, 4, 'ITAPUA');
insert into provincia values(default, 4, 'ÑEEMBUCÚ');
insert into provincia values(default, 4, 'VILLARRICA');
insert into provincia values(default, 4, 'MISIONES');
insert into provincia values(default, 5, 'SORIANO');
insert into provincia values(default, 5, 'DURAZNO');
insert into provincia values(default, 6, 'REGION METROPOLITANA DE SANTIAGO');
insert into provincia values(default, 9, 'DISTRITO CAPITAL');
insert into provincia values(default, 11, 'ISLA DE FRANCIA');
insert into provincia values(default, 11, 'PIRINEOS ORIENTALES');
insert into provincia values(default, 12, 'HESSE');
insert into provincia values(default, 12, 'BAJA SAJONIA');
insert into provincia values(default, 12, 'ALTA SILESIA');
insert into provincia values(default, 12, 'BAVIERA');
insert into provincia values(default, 13, 'PROVINCIA DE VILNA');
insert into provincia values(default, 14, 'CATALUÑA');
insert into provincia values(default, 14, 'BARCELONA');
insert into provincia values(default, 15, 'DEPARTAMENTO DE MANAGUA');
insert into provincia values(default, 15, 'ZACATECAS');
insert into provincia values(default, 18, 'ALLEGHENY');
insert into provincia values(default, 17, 'CALIFORNIA');
insert into provincia values(default, 18, 'ROMA');
insert into provincia values(default, 18, 'ASCOLI PICENO');
insert into provincia values(default, 19, 'SIN PROVINCIA');
insert into provincia values(default, 20, 'WILNO');

insert into localidad values(default, 1, 'SIN LOCALIDAD');
insert into localidad values(default, 2, 'VILLA DE MAYO');
insert into localidad values(default, 2, 'OLAVARRIA');
insert into localidad values(default, 2, 'VILLALONGA');
insert into localidad values(default, 2, 'FLORIDA');
insert into localidad values(default, 2, 'VICENTE LOPEZ');
insert into localidad values(default, 2, 'FLORENCIO VARELA');
insert into localidad values(default, 2, 'HAEDO');
insert into localidad values(default, 2, 'HURLINGHAM');
insert into localidad values(default, 2, 'JOSE C. PAZL');
insert into localidad values(default, 2, 'LUJAN');
insert into localidad values(default, 2, 'LOMAS DE ZAMORA');
insert into localidad values(default, 2, 'MORENO');
insert into localidad values(default, 2, 'MORÓN');
insert into localidad values(default, 2, 'NECOCHEA');
insert into localidad values(default, 2, 'QUILMES');
insert into localidad values(default, 2, 'LINCOLN');
insert into localidad values(default, 2, 'LA PLATA');
insert into localidad values(default, 2, 'PUAN');
insert into localidad values(default, 2, 'LOBERIAS');
insert into localidad values(default, 2, 'AVELLANEDA');
insert into localidad values(default, 2, 'TRISTAN SUAREZ');
insert into localidad values(default, 2, 'RAUCH');
insert into localidad values(default, 2, 'PIÑEYRO');
insert into localidad values(default, 2, 'SAN ISIDRO');
insert into localidad values(default, 2, 'WILDE');
insert into localidad values(default, 2, 'BANFIELD');
insert into localidad values(default, 2, 'ZÁRATE');
insert into localidad values(default, 2, 'GENERAL SARMIENTO');
insert into localidad values(default, 2, 'BAHIA BLANCA');
insert into localidad values(default, 2, 'GENERAL SAN MARTIN');
insert into localidad values(default, 2, 'CARLOS CASARES');
insert into localidad values(default, 2, 'AMEGHINO');
insert into localidad values(default, 2, 'SAN JUSTO');
insert into localidad values(default, 2, 'CARMEN DE PATAGONES');
insert into localidad values(default, 2, 'ROJAS');
insert into localidad values(default, 2, 'BERNAL OESTE');
insert into localidad values(default, 2, 'SAN MIGUEL DEL MONTE');
insert into localidad values(default, 2, 'CHIVILCOY');
insert into localidad values(default, 2, 'TANDIL');
insert into localidad values(default, 2, 'DOLORES');
insert into localidad values(default, 2, 'TIGRE');
insert into localidad values(default, 2, 'AZUL');
insert into localidad values(default, 2, 'VERONICA');
insert into localidad values(default, 2, 'TRES ARROYOS');
insert into localidad values(default, 2, 'CAMPO DE MAYO');
insert into localidad values(default, 2, 'CIUDADELA');
insert into localidad values(default, 2, 'MARTIN CORONADO');
insert into localidad values(default, 2, 'LOMA HERMOSA');
insert into localidad values(default, 2, 'MERLO');
insert into localidad values(default, 2, 'LANUS');
insert into localidad values(default, 2, 'JOSE LEON SUAREZ');
insert into localidad values(default, 2, 'CASEROS');
insert into localidad values(default, 2, 'TRENQUE LAUQUEN');
insert into localidad values(default, 2, 'SAN FERNANDO');
insert into localidad values(default, 2, 'MONTE');
insert into localidad values(default, 2, 'VILLA BALLESTER');
insert into localidad values(default, 2, 'ALMIRANTE BROWN');
insert into localidad values(default, 2, 'MANUEL B. GONNET');
insert into localidad values(default, 2, 'CAPITAL FEDERAL');
insert into localidad values(default, 2, 'BELLA VISTA');
insert into localidad values(default, 2, 'RAMOS MEJIA');
insert into localidad values(default, 2, 'CIUDAD AUTONOMA DE BUENOS AIRES');
insert into localidad values(default, 2, 'PERGAMINO');
insert into localidad values(default, 2, 'CHACABUCO');
insert into localidad values(default, 2, 'NO ESPECIFICADA');
insert into localidad values(default, 2, 'MAR DEL PLATA');
insert into localidad values(default, 2, 'SAN MIGUEL');
insert into localidad values(default, 2, 'SAN NICOLAS DE LOS ARROYOS');
insert into localidad values(default, 3, 'SAN FERNANDO DEL VALLE DE CATAMARCA');
insert into localidad values(default, 3, 'NO ESPECIFICADA');
insert into localidad values(default, 4, 'COLONIA ELISA');
insert into localidad values(default, 4, 'PAMPA DEL INFIERNO');
insert into localidad values(default, 4, 'AVIA TERAI');
insert into localidad values(default, 4, 'LAS BREÑAS');
insert into localidad values(default, 4, 'MARGARITA BELEN');
insert into localidad values(default, 4, 'VILLA ANGELA');
insert into localidad values(default, 4, 'TACO POZO');
insert into localidad values(default, 4, 'ROQUE SAENZ PEÑA');
insert into localidad values(default, 4, 'RESISTENCIA');
insert into localidad values(default, 4, 'PRESIDENCIA DE LA PLAZA');
insert into localidad values(default, 4, 'LAS PALMAS');
insert into localidad values(default, 4, 'JUAN JOSE.CASTELLI');
insert into localidad values(default, 4, 'GANCEDO');
insert into localidad values(default, 4, 'GRAL. JOSE DE SAN MARTIN');
insert into localidad values(default, 4, 'CHARATA');
insert into localidad values(default, 4, 'BARRANQUERAS');
insert into localidad values(default, 4, 'QUITILIPI');
insert into localidad values(default, 4, 'NO ESPECIFICADA');
insert into localidad values(default, 5, 'TRELEW');
insert into localidad values(default, 5, 'ESQUEL');
insert into localidad values(default, 5, 'RAWSON');
insert into localidad values(default, 5, 'PUERTO MADRYN');
insert into localidad values(default, 5, 'NO ESPECIFICADA');
insert into localidad values(default, 5, 'COMODORO RIVADAVIA');
insert into localidad values(default, 6, 'LA PLAYOSA');
insert into localidad values(default, 6, 'CORDOBA');
insert into localidad values(default, 6, 'VILLA CARLOS PAZ');
insert into localidad values(default, 6, 'CRUZ ALTA');
insert into localidad values(default, 6, 'LABOULAYE');
insert into localidad values(default, 6, 'LA CARLOTA');
insert into localidad values(default, 6, 'RIO CUARTO');
insert into localidad values(default, 6, 'RIO SEGUNDO');
insert into localidad values(default, 6, 'RIO TERCERO');
insert into localidad values(default, 6, 'NO ESPECIFICADA');
insert into localidad values(default, 6, 'SAN FRANCISCO');
insert into localidad values(default, 6, 'UNQUILLO');
insert into localidad values(default, 6, 'VILLA DOLORES');
insert into localidad values(default, 6, 'BALLESTEROS');
insert into localidad values(default, 6, 'ALEJO LEDEZMA');
insert into localidad values(default, 6, 'VILLA María');
insert into localidad values(default, 6, 'CONDORES');
insert into localidad values(default, 6, 'VILLA BUSTOS');
insert into localidad values(default, 6, 'COLONIA BISMARCK');
insert into localidad values(default, 6, 'JESUS MARIA');
insert into localidad values(default, 6, 'EL QUEBRACHO');
insert into localidad values(default, 7, 'VIRASORO');
insert into localidad values(default, 7, 'PASO DE LA PATRIA');
insert into localidad values(default, 7, 'PASO DE LOS LIBRES');
insert into localidad values(default, 7, 'SAN MIGUEL');
insert into localidad values(default, 7, 'CAABY POY');
insert into localidad values(default, 7, 'EMPEDRADO');
insert into localidad values(default, 7, 'ITATI');
insert into localidad values(default, 7, 'NO ESPECIFICADA');
insert into localidad values(default, 7, 'COLONIA URIBURU');
insert into localidad values(default, 7, 'CORRIENTES');
insert into localidad values(default, 7, 'LORETO');
insert into localidad values(default, 7, 'MERCEDES');
insert into localidad values(default, 7, 'MOCORETA');
insert into localidad values(default, 7, 'SAN CARLOS');
insert into localidad values(default, 7, 'BELLA VISTA');
insert into localidad values(default, 7, 'CONCEPCION');
insert into localidad values(default, 7, 'CURUZU CUATIA');
insert into localidad values(default, 7, 'ESQUINA');
insert into localidad values(default, 7, 'GOYA');
insert into localidad values(default, 7, 'LA CRUZ');
insert into localidad values(default, 7, 'MONTE CASEROS');
insert into localidad values(default, 7, 'SAN LUIS DEL PALMAR');
insert into localidad values(default, 7, 'SALADAS');
insert into localidad values(default, 7, 'SAN ROQUE');
insert into localidad values(default, 7, 'GDOR. ING. VALENTIN VIRASORO');
insert into localidad values(default, 7, 'GARRUCHOS');
insert into localidad values(default, 7, 'COLONIA LIEBIG');
insert into localidad values(default, 7, 'ITUZAINGO');
insert into localidad values(default, 7, 'SANTO TOME');
insert into localidad values(default, 7, 'SANTA LUCIA');
insert into localidad values(default, 7, 'ALVEAR');
insert into localidad values(default, 8, 'VICTORIA');
insert into localidad values(default, 8, 'VILLA ELISA');
insert into localidad values(default, 8, 'VILLAGUAY');
insert into localidad values(default, 8, 'VILLA LIBERTADOR SAN MARTIN');
insert into localidad values(default, 8, 'VILLA SAN MARCIAL');
insert into localidad values(default, 8, 'ROSARIO DEL TALA');
insert into localidad values(default, 8, 'NOGOYA');
insert into localidad values(default, 8, 'PARANA');
insert into localidad values(default, 8, 'FEDERACION');
insert into localidad values(default, 8, 'GUALEGUAY');
insert into localidad values(default, 8, 'GUALEGUAYCHU');
insert into localidad values(default, 8, 'CONCORDIA');
insert into localidad values(default, 8, 'CONCEPCION DEL URUGUAY');
insert into localidad values(default, 8, 'COLON');
insert into localidad values(default, 8, 'BASAVILBASO');
insert into localidad values(default, 8, 'BOVRIL');
insert into localidad values(default, 8, 'DIAMANTE');
insert into localidad values(default, 8, 'SANTA ANITA');
insert into localidad values(default, 8, 'PEHUAJO NORTE');
insert into localidad values(default, 8, 'LA PAZ');
insert into localidad values(default, 8, 'CHAJARI');
insert into localidad values(default, 8, 'NO ESPECIFICADA');
insert into localidad values(default, 9, 'COLONIA JUANITA');
insert into localidad values(default, 9, 'PIRANE');
insert into localidad values(default, 9, 'CLORINDA');
insert into localidad values(default, 9, 'NO ESPECIFICADA');
insert into localidad values(default, 9, 'EL COLORADO');
insert into localidad values(default, 9, 'FORMOSA');
insert into localidad values(default, 10, 'NO ESPECIFICADA');
insert into localidad values(default, 10, 'SAN SALVADOR DE JUJUY');
insert into localidad values(default, 11, 'COLONIA BARÓN');
insert into localidad values(default, 11, 'NO ESPECIFICADA');
insert into localidad values(default, 11, 'SANTA ROSA');
insert into localidad values(default, 12, 'MILAGRO');
insert into localidad values(default, 12, 'VILLA BUSTOS');
insert into localidad values(default, 12, 'NO ESPECIFICADA');
insert into localidad values(default, 12, 'LOS PALACIOS');
insert into localidad values(default, 12, 'LA RIOJA');
insert into localidad values(default, 13, 'NO ESPECIFICADA');
insert into localidad values(default, 13, 'MENDOZA');
insert into localidad values(default, 13, 'SAN RAFAEL');
insert into localidad values(default, 13, 'SAN MARTIN');
insert into localidad values(default, 13, 'VILLA SECA');
insert into localidad values(default, 13, 'GENERAL ALVEAR');
insert into localidad values(default, 13, 'GODOY CRUZ');
insert into localidad values(default, 14, 'SAN JOSE');
insert into localidad values(default, 14, 'TRES ESQUINAS');
insert into localidad values(default, 14, 'SAN JAVIER');
insert into localidad values(default, 14, 'SAN IGNACIO');
insert into localidad values(default, 14, 'SAN ANTONIO');
insert into localidad values(default, 14, 'COLONIA CAAGUAZU');
insert into localidad values(default, 14, 'RUIZ DE MONTOYA');
insert into localidad values(default, 14, 'PUERTO RICO');
insert into localidad values(default, 14, 'PUERTO PIRAY');
insert into localidad values(default, 14, 'PUERTO LIBERTAD');
insert into localidad values(default, 14, 'PUERTO LEONI');
insert into localidad values(default, 14, 'PUERTO IGUAZU');
insert into localidad values(default, 14, 'PUERTO ESPERANZA');
insert into localidad values(default, 14, 'PIÑALITO SUR');
insert into localidad values(default, 14, 'PROFUNDIDAD');
insert into localidad values(default, 14, 'PANAMBI');
insert into localidad values(default, 14, 'PUERTO GISELA');
insert into localidad values(default, 14, 'PUERTO ESPAÑA');
insert into localidad values(default, 14, 'COLONIA YABEBIRI');
insert into localidad values(default, 14, 'SIERRA DE SAN JOSE');
insert into localidad values(default, 14, 'PICADA SARGENTO CABRAL');
insert into localidad values(default, 14, '25 DE MAYO');
insert into localidad values(default, 14, 'GUAYABERA');
insert into localidad values(default, 14, 'CUÑA PIRU');
insert into localidad values(default, 14, 'ARISTOBULO DEL VALLE');
insert into localidad values(default, 14, 'POSADAS');
insert into localidad values(default, 14, 'PIÑALITO NORTE');
insert into localidad values(default, 14, 'EL SOBERBIO');
insert into localidad values(default, 14, 'GARUHAPE');
insert into localidad values(default, 14, 'PICADA FINLANDESA');
insert into localidad values(default, 14, 'FACHINAL');
insert into localidad values(default, 14, 'ELDORADO');
insert into localidad values(default, 14, 'FNO. AMEGHINO');
insert into localidad values(default, 14, 'GENERAL URQUIZA');
insert into localidad values(default, 14, 'COLONIA AURORA');
insert into localidad values(default, 14, '9 DE JULIO');
insert into localidad values(default, 14, 'COLONIA GUARANI');
insert into localidad values(default, 14, 'BONPLAND');
insert into localidad values(default, 14, 'EL ALCAZAR');
insert into localidad values(default, 14, 'SALTO ENCANTADO');
insert into localidad values(default, 14, 'MONTEAGUDO');
insert into localidad values(default, 14, 'TRES CAPONES');
insert into localidad values(default, 14, 'SANTO PIPO');
insert into localidad values(default, 14, 'SANTIAGO DE LINIERS');
insert into localidad values(default, 14, 'SANTA MARIA');
insert into localidad values(default, 14, 'SANTA ANA');
insert into localidad values(default, 14, 'SAN VICENTE');
insert into localidad values(default, 14, 'SAN PEDRO');
insert into localidad values(default, 14, 'SAN MARTIN');
insert into localidad values(default, 14, 'COLONIA OASIS');
insert into localidad values(default, 14, 'MACHADIÑO');
insert into localidad values(default, 14, 'COLONIA DELICIA');
insert into localidad values(default, 14, 'LAS VERTIENTES');
insert into localidad values(default, 14, 'ITACARUARE');
insert into localidad values(default, 14, 'COLONIA POLANA');
insert into localidad values(default, 14, 'HIPOLITO IRIGOYEN');
insert into localidad values(default, 14, 'GUARANI');
insert into localidad values(default, 14, 'GOBENADOR ROCA');
insert into localidad values(default, 14, 'GOBERNADOR LOPEZ');
insert into localidad values(default, 14, 'COLONIA VICTORIA');
insert into localidad values(default, 14, 'PUERTO BEMBERG');
insert into localidad values(default, 14, 'GARUPA');
insert into localidad values(default, 14, 'COLONIA WANDA');
insert into localidad values(default, 14, 'CONCEPCION DE LA SIERRA');
insert into localidad values(default, 14, 'CORPUS');
insert into localidad values(default, 14, 'DOS ARROYOS');
insert into localidad values(default, 14, 'COLONIA GISELA');
insert into localidad values(default, 14, 'DOS DE MAYO');
insert into localidad values(default, 14, 'SAN JUAN DE LA SIERRA');
insert into localidad values(default, 14, 'ALBA POSSE');
insert into localidad values(default, 14, 'ALMAFUERTE');
insert into localidad values(default, 14, 'APOSTOLES');
insert into localidad values(default, 14, 'ARROYO DEL MEDIO');
insert into localidad values(default, 14, 'AZARA');
insert into localidad values(default, 14, 'BERNARDO DE IRIGOYEN');
insert into localidad values(default, 14, 'NO ESPECIFICADA');
insert into localidad values(default, 14, 'CAA - YARI');
insert into localidad values(default, 14, 'POZO AZUL');
insert into localidad values(default, 14, 'CAMPO GRANDE');
insert into localidad values(default, 14, 'LIBERTADOR GENERAL SAN MARTIN');
insert into localidad values(default, 14, 'SAN FRANCISCO DE ASIS');
insert into localidad values(default, 14, 'CAMPO RAMON');
insert into localidad values(default, 14, 'JARDIN AMERICA');
insert into localidad values(default, 14, 'CAMPO VIERA');
insert into localidad values(default, 14, 'SANTA RITA');
insert into localidad values(default, 14, 'OBERA');
insert into localidad values(default, 14, 'OLEGARIO VICTOR ANDRADE');
insert into localidad values(default, 14, 'MONTECARLO');
insert into localidad values(default, 14, 'MOJON GRANDE');
insert into localidad values(default, 14, 'MARTIRES');
insert into localidad values(default, 14, 'INVERNADA GRANDE');
insert into localidad values(default, 14, 'CANDELARIA');
insert into localidad values(default, 14, 'CAPIOVI');
insert into localidad values(default, 14, 'DOS HERMANAS');
insert into localidad values(default, 14, 'PICADA YAPEYU');
insert into localidad values(default, 14, 'LOS HELECHOS');
insert into localidad values(default, 14, 'LORETO');
insert into localidad values(default, 14, 'LEANDRO N. ALEM');
insert into localidad values(default, 14, 'CARAGUATAY');
insert into localidad values(default, 14, 'CERRO AZUL');
insert into localidad values(default, 14, 'CERRO CORA');
insert into localidad values(default, 14, 'COMANDANTE ANDRESITO');
insert into localidad values(default, 14, 'GENERAL ALVEAR');
insert into localidad values(default, 14, 'COLONIA ALBERDI');
insert into localidad values(default, 14, 'GOBERNADOR LANUSSE');
insert into localidad values(default, 14, 'PARADA LEIS');
insert into localidad values(default, 14, 'SAN ALBERTO');
insert into localidad values(default, 14, 'PUERTO NARANJITO');
insert into localidad values(default, 14, 'PUERTO LONDERO');
insert into localidad values(default, 14, 'SAN ISIDRO');
insert into localidad values(default, 15, 'NO ESPECIFICADA');
insert into localidad values(default, 15, 'SAN CARLOS DE BARILOCHE');
insert into localidad values(default, 15, 'INGENIERO HUERGO');
insert into localidad values(default, 15, 'ALLEN');
insert into localidad values(default, 15, 'SIERRA GRANDE');
insert into localidad values(default, 15, 'VILLA REGINA');
insert into localidad values(default, 16, 'GENERAL J DE SAN MARTIN');
insert into localidad values(default, 16, 'CACHI');
insert into localidad values(default, 16, 'SALTA');
insert into localidad values(default, 16, 'NO ESPECIFICADA');
insert into localidad values(default, 16, 'TARTAGAL');
insert into localidad values(default, 17, 'JACHAL');
insert into localidad values(default, 17, 'SAN JUAN');
insert into localidad values(default, 17, 'RIVADAVIA');
insert into localidad values(default, 17, 'NO ESPECIFICADA');
insert into localidad values(default, 18, 'NO ESPECIFICADA');
insert into localidad values(default, 18, 'VILLA MERCEDES');
insert into localidad values(default, 19, 'RIO GALLEGOS');
insert into localidad values(default, 19, 'PUERTO SAN JULIAN');
insert into localidad values(default, 19, 'NO ESPECIFICADA');
insert into localidad values(default, 20, 'SAN JUSTO');
insert into localidad values(default, 20, 'RECONQUISTA');
insert into localidad values(default, 20, 'RAFAELA');
insert into localidad values(default, 20, 'SAN CARLOS CENTRO');
insert into localidad values(default, 20, 'MONJE');
insert into localidad values(default, 20, 'EL TREBOL');
insert into localidad values(default, 20, 'ARRUFO');
insert into localidad values(default, 20, 'ARROYO SECO');
insert into localidad values(default, 20, 'SAN JERONIMO');
insert into localidad values(default, 20, 'MACIEL');
insert into localidad values(default, 20, 'RUFINO');
insert into localidad values(default, 20, 'CORONDA');
insert into localidad values(default, 20, 'VILLA ANA');
insert into localidad values(default, 20, 'ROSARIO');
insert into localidad values(default, 20, 'SAN LORENZO');
insert into localidad values(default, 20, 'VERA');
insert into localidad values(default, 20, 'VENADO TUERTO');
insert into localidad values(default, 20, 'SUNCHALES');
insert into localidad values(default, 20, 'SANTA FE');
insert into localidad values(default, 20, 'SAN CRISTOBAL');
insert into localidad values(default, 21, 'AÑATUYA');
insert into localidad values(default, 21, 'LA BANDA');
insert into localidad values(default, 21, 'SANTIAGO DEL ESTERO');
insert into localidad values(default, 21, 'PAMPA DE LOS GUANACOS');
insert into localidad values(default, 22, 'RIO GRANDE');
insert into localidad values(default, 22, 'USHUAIA');
insert into localidad values(default, 23, 'JUAN B.ALBERDI');
insert into localidad values(default, 23, 'EL BRACHO');
insert into localidad values(default, 23, 'SAN MIGUEL DE TUCUMAN');
insert into localidad values(default, 24, 'SAN MARTIN DE LOS ANDES');
insert into localidad values(default, 24, 'VILLA LANGOSTURA');
insert into localidad values(default, 24, 'JUNIN DE LOS ANDES');
insert into localidad values(default, 24, 'CUTRAL CO');
insert into localidad values(default, 24, 'NO ESPECIFICADA');
insert into localidad values(default, 25, 'SAN MAURICIO');
insert into localidad values(default, 25, 'GENERAL ARTIGAS');
insert into localidad values(default, 25, 'BELLA VISTA');
insert into localidad values(default, 25, 'HOHENAU');
insert into localidad values(default, 25, 'GENERAL DELGADO');
insert into localidad values(default, 25, 'CARMEN DEL PARANA');
insert into localidad values(default, 25, 'CORONEL BOGADO');
insert into localidad values(default, 25, 'ENCARNACION');
insert into localidad values(default, 25, 'PIRAPO');
insert into localidad values(default, 25, 'JESÚS');
insert into localidad values(default, 25, 'SAN COSME Y DAMIAN');
insert into localidad values(default, 25, 'SAN PEDRO DEL PARANA');
insert into localidad values(default, 25, 'SANTO DOMINGO');
insert into localidad values(default, 25, 'CAMBYRETA');
insert into localidad values(default, 25, 'SALITRE-CUE');
insert into localidad values(default, 25, 'MAYOR OTAÑO');
insert into localidad values(default, 25, 'PUERTO CANTERA');
insert into localidad values(default, 26, 'QUYQUYHO');
insert into localidad values(default, 26, 'SAPUCAI');
insert into localidad values(default, 26, 'YBYTYMÍ');
insert into localidad values(default, 26, 'CAAPUCU');
insert into localidad values(default, 26, 'TEBICUARY-MI');
insert into localidad values(default, 26, 'YBYCUÍ');
insert into localidad values(default, 26, 'MBUYAPEY');
insert into localidad values(default, 27, 'FULGENCIO YEGROS');
insert into localidad values(default, 27, 'SAN JUAN NEPOMUCENO');
insert into localidad values(default, 27, 'YUTY');
insert into localidad values(default, 27, 'GENERAL HIGINIO MORINIGO');
insert into localidad values(default, 27, 'ABAI');
insert into localidad values(default, 28, 'COLONIA INDEPENDENCIA');
insert into localidad values(default, 28, 'ITURBE');
insert into localidad values(default, 28, 'BORJA');
insert into localidad values(default, 28, 'CHARARA');
insert into localidad values(default, 28, 'VILLARICA');
insert into localidad values(default, 29, 'ASUNCION');
insert into localidad values(default, 30, 'SOLTAU');
insert into localidad values(default, 32, 'PIA');
insert into localidad values(default, 33, 'SIN LOCALIDAD');
insert into localidad values(default, 34, 'SABADELL');
insert into localidad values(default, 36, 'SAN JUAN BAUTISTA');
insert into localidad values(default, 36, 'SAN MIGUEL');
insert into localidad values(default, 36, 'SANTA MARIA');
insert into localidad values(default, 36, 'SAN PATRICIO');
insert into localidad values(default, 37, 'CORONEL OVIEDO');
insert into localidad values(default, 37, 'SAN JOSE DE LOS ARROYOS');
insert into localidad values(default, 38, 'AREGUÁ');
insert into localidad values(default, 38, 'GUARAMBARE');
insert into localidad values(default, 38, 'YPACARAI');
insert into localidad values(default, 38, 'VILLA ELISA');
insert into localidad values(default, 39, 'PORTO LUCENA');
insert into localidad values(default, 39, 'SANTO CRISTO');
insert into localidad values(default, 39, 'SAO LUIZ GONZAGA');
insert into localidad values(default, 39, 'SANTA MARIA');
insert into localidad values(default, 39, 'PASSO FUNDO');
insert into localidad values(default, 39, 'SANTO ANGELO');
insert into localidad values(default, 39, 'CARASINHO');
insert into localidad values(default, 39, 'CRISSIUMAL');
insert into localidad values(default, 39, 'IJUI');
insert into localidad values(default, 39, 'SAN NICOLAS');
insert into localidad values(default, 39, 'NONOAI');
insert into localidad values(default, 39, 'HORIZONTINA');
insert into localidad values(default, 39, 'SANTA ROSA');
insert into localidad values(default, 40, 'MANAGUA');
insert into localidad values(default, 41, 'ZACATECAS');
insert into localidad values(default, 42, 'PITTSBURGH');
insert into localidad values(default, 43, 'SAN ANTONIO');
insert into localidad values(default, 43, 'MEDIANEIRA');
insert into localidad values(default, 44, 'BOGOTA');
insert into localidad values(default, 45, 'SIN LOCALIDAD');
insert into localidad values(default, 46, 'WILNO');
insert into localidad values(default, 47, 'RESENDE');
insert into localidad values(default, 48, 'SAN PABLO');
insert into localidad values(default, 49, 'PONTE SERRADA');
insert into localidad values(default, 49, 'PORTO XAVIER');
insert into localidad values(default, 49, 'DIONISÍO CERQUEIRA');
insert into localidad values(default, 49, 'ROMELANDIA');
insert into localidad values(default, 49, 'CHAPECO');
insert into localidad values(default, 50, 'DOLORES');
insert into localidad values(default, 51, 'LOS ANGELES');
insert into localidad values(default, 52, 'HERNANDARIAS');
insert into localidad values(default, 53, 'SIN LOCALIDAD');
insert into localidad values(default, 54, 'SIN LOCALIDAD');
insert into localidad values(default, 55, 'LARANJEIRAS');
insert into localidad values(default, 56, 'PONTA PORA');
insert into localidad values(default, 57, 'GRABOCIN');
insert into localidad values(default, 58, 'SANTIAGO');
insert into localidad values(default, 60, 'DURAZNO');
insert into localidad values(default, 61, 'FERMO');
insert into localidad values(default, 62, 'KASSEL');
insert into localidad values(default, 63, 'PILAR');



insert into tipo_documento values(default, 'S/T' ,'Sin Tipo de Documento');
insert into tipo_documento values(default, 'CI' ,'CEDULA DE IDENTIDAD');
insert into tipo_documento values(default, 'DNI' ,'DOCUMENTO NACIONAL DE IDENTIDAD');
insert into tipo_documento values(default, 'LC' ,'LIBRETA CIVICA');
insert into tipo_documento values(default, 'LE' ,'LIBRETA DE ENROLAMIENTO');

insert into estado_civil values(default, 'Sin Estado Civil');
insert into estado_civil values(default, 'CASADO');
insert into estado_civil values(default, 'DIVORCIADO');
insert into estado_civil values(default, 'SOLTERO');
insert into estado_civil values(default, 'VIUDO');
insert into estado_civil values(default, 'SEPARADO DE HECHO');

insert into tipo_telefono values(default, 'FIJO');
insert into tipo_telefono values(default, 'CELULAR');
insert into tipo_telefono values(default, 'FAX');


insert into tipo_detalle_viatico values(default, 'Sin Motivo');
insert into tipo_detalle_viatico values(default, 'COMBUSTIBLE');
insert into tipo_detalle_viatico values(default, 'HOSPEDAJE');
